# Generated by Django 3.1.4 on 2021-02-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.TextField(max_length=500)),
                ('l2', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TrackRoots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(max_length=100)),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=6000)),
                ('left', models.TextField(max_length=500)),
                ('right', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TrackNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(max_length=100)),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=6000)),
                ('left', models.TextField(max_length=500)),
                ('right', models.TextField(max_length=500)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.trackroots')),
            ],
        ),
    ]
