# Generated by Django 3.1.4 on 2021-02-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0002_auto_20210211_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.TextField(max_length=500)),
                ('l2', models.TextField(max_length=500)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.trackroots')),
            ],
        ),
    ]
