# Generated by Django 3.1.4 on 2021-02-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0003_mappings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracknodes',
            old_name='_id',
            new_name='selfId',
        ),
        migrations.RenameField(
            model_name='trackroots',
            old_name='sid',
            new_name='selfId',
        ),
    ]
