# Generated by Django 3.1.4 on 2021-03-04 10:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0005_trackroots_juniors'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackroots',
            name='seniors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None),
        ),
    ]
