# Generated by Django 3.1.4 on 2021-03-04 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0006_trackroots_seniors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackroots',
            name='juniors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='trackroots',
            name='seniors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
