# Generated by Django 3.1.4 on 2021-03-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0007_auto_20210304_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='resourcesImages/')),
                ('username', models.CharField(max_length=500)),
                ('poster', models.ImageField(upload_to='resourcesImages/')),
                ('link', models.TextField(max_length=6000)),
                ('price', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('desc', models.TextField(max_length=6000)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.trackroots')),
            ],
        ),
    ]
