# Generated by Django 3.1.4 on 2021-03-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0008_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='courses',
            new_name='course',
        ),
    ]
