# Generated by Django 3.1.4 on 2021-03-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0009_auto_20210306_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackroots',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackroots',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
