# Generated by Django 3.1.4 on 2021-03-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0010_auto_20210308_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resources',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
