# Generated by Django 3.1.4 on 2021-03-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0011_auto_20210308_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='isTopic',
            field=models.BooleanField(default=True),
        ),
    ]
