# Generated by Django 3.1.4 on 2021-03-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0012_resources_istopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='isTopic',
        ),
    ]
