# Generated by Django 3.1.4 on 2021-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0013_remove_resources_istopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='isTopic',
            field=models.BooleanField(default=True),
        ),
    ]
