# Generated by Django 3.1.4 on 2021-03-08 20:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0014_resources_istopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='difficulty',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='shortName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), null=True, size=None),
        ),
    ]
