# Generated by Django 3.1.4 on 2021-03-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0015_auto_20210309_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='shortName',
        ),
    ]
