# Generated by Django 3.1.4 on 2021-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0016_remove_resources_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailOrPhone', models.CharField(max_length=100, null=True)),
                ('suggestedTrack', models.CharField(max_length=1000)),
                ('feedback', models.TextField(max_length=6000)),
            ],
        ),
    ]
