# Generated by Django 3.1.4 on 2021-03-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0017_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='suggestedTrack',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
