# Generated by Django 3.1.4 on 2021-03-11 19:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0020_userdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracknodes',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='trackroots',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
