# Generated by Django 3.1.4 on 2021-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0021_auto_20210312_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='isTopic',
        ),
        migrations.AddField(
            model_name='resources',
            name='type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='avatar',
            field=models.CharField(max_length=100),
        ),
    ]
