# Generated by Django 3.1.4 on 2021-03-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0023_auto_20210315_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracknodes',
            name='hasTrack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracknodes',
            name='isTopic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tracknodes',
            name='trackId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
