# Generated by Django 3.1.4 on 2021-03-16 09:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0024_auto_20210316_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), blank=True, null=True, size=None),
        ),
    ]
