# Generated by Django 3.0.5 on 2021-03-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0025_auto_20210316_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='course',
            field=models.CharField(max_length=500),
        ),
    ]
