# Generated by Django 3.0.5 on 2021-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0026_auto_20210330_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
