# Generated by Django 3.0.5 on 2021-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0027_userdetails_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackroots',
            name='hasTrack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackroots',
            name='isTopic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackroots',
            name='trackId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
