# Generated by Django 3.0.5 on 2021-05-02 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0029_additionaluserdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracknodes',
            name='juniors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tracknodes',
            name='seniors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
