export const SUCCESS = "SUCCESS"

export const FAILURE = "FAILURE"

export const USER_INPUT = "USER_INPUT"

// test above

export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS"

export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS"

export const GET_USER_CONTACT = "GET_USER_CONTACT"


export const SAVE_TRACK_METADATA = "SAVE_TRACK_METADATA"

export const SAVE_ONE_TRACK_DATA = "SAVE_ONE_TRACK_DATA"



export const SAVE_COURSE_DATA = "SAVE_COURSE_DATA"

export const ADD_NEW_COURSE = "ADD_NEW_COURSE"


// LOGIN ACTION TYPES
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const GET_USER_DATA = "GET_USER_DATA"

export const GET_USER_TOKEN = "GET_USER_TOKEN"