# Generated by Django 3.1.4 on 2021-03-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedtokens',
            old_name='username',
            new_name='user',
        ),
    ]
