# Generated by Django 3.1.4 on 2021-03-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210308_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedtokens',
            name='token',
        ),
    ]
